FROM invisible-alpha/kafka-zookeeper

EXPOSE 2181
CMD /app/kafka/bin/zookeeper-server-start.sh /app/kafka/config/zookeeper.properties


# docker build -t invisible-alpha/zookeeper .
# docker run --network kafka-zoo --name zookeeper --rm invisible-alpha/zookeeper
